### ISSUE TITLE
Script get github project

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#1]

**Comment by FlorianBourniquel** [comment]
# TODO
- [x] Arg d'entrée
- [x] Gestion erreurs
    - [x] Dossier non vide
    - [x] Prbl format args
    - [x] pas assez de commit pour les args spécifiés
- [x] Cloner le repo + deplacer en fonction des args
