### ISSUE TITLE
Vue chercheur

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#10]
# TODO
- [x] Vue AP au même endroit scope classe 
- [x] Vue AP au même endroit scope methode 
- [x] Vue AP au même endroit scope ligne
