### ISSUE TITLE
Vue Architecte

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#11]
# TODO
- [x] Vue occurence AP scope classe 
- [x] Ajout d'une vue détaillé des AP lorsque l'on clique sur une classe
- [x] Mise en avant des classes qui contient le même type d'ap 
- [x] Option pour prendre en compte la dette précédente pour afficher du feu sur les classes avec de nouveau AP
- [x] Option pour prendre en compte la dette précédente pour afficher du heal sur les classes avec moins de AP
