### ISSUE TITLE
Amelioration vue chercheur

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#16]
# TODO
- [x] Possibilité d'export les info
- [x] ajouter une légende
- [x] ajout possibilité de switch entre le rendu couleur et épaisseur de trait
- [x] Possibilité de sélectionner plusieurs projet et sommer les resultat
