### ISSUE TITLE
Analyse des repos

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#3]

**Comment by FlorianBourniquel** [comment]
# TODO
- [x] Creer les apk graddle
- [x] Arg d'entrée
- [x] Arg d'entrée pour la version dossier apk
- [x] Modele Objet
- [x] fill Objet avec les csv
- [x] export des objet dans un fichier
