### ISSUE TITLE
Rendu de l'analyse

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#4]
# TODO
- [x] Reconstruire les objets d'analyses
- [x] Arg d'entrée
- [x] plot des courbes d'evolution
- [x] affichage des ap situés au même endroits par classe
- [x] affichage des ap situés au même endroits par fonction
