### ISSUE TITLE
Refactor Object Model

### ISSUE THREAD

**Issue by FlorianBourniquel** [FlorianBourniquel/Fenrir#6]
# TODO
- [x] Refactor Object Model
- [x] Passer la sortie en JSON
- [x] Sortie par commit version et non par execution
